"""
v4/api/demo_dag.py — DAG démo auto-démarré au boot de l'API.
"""
from __future__ import annotations
from v4.api.models import DAGSpec, NodeSpec, EdgeSpec

DEMO_DAG = DAGSpec(
    dag_id="demo_v4",
    asset="BTC/USDT",
    nodes=[
        NodeSpec(id="btc_asset", type="AssetDef",
                 params={"symbol": "BTC/USDT", "exchange": "binance", "capital_usd": 10000, "fraction": 0.02}),
        NodeSpec(id="btc_data", type="LoadMultiTF",
                 params={"symbol": "BTC/USDT", "days_5m": 90, "days_1h": 100, "exchange": "binance"}),
        NodeSpec(id="btc_features", type="ComputeFeatures", params={}),
        NodeSpec(id="btc_norm", type="Normalize", params={"window": 500}),
        NodeSpec(id="btc_regime", type="RegimeHMM", params={"n_states": 3}),
        NodeSpec(id="btc_trend", type="TrendFilter",
                 params={"timeframe_resample": "4h", "sma_fast": 20, "sma_slow": 50}),
        NodeSpec(id="btc_signal", type="SignalLogReg",
                 params={"calibrate": True, "train_fraction": 0.70, "horizon_bars": 48,
                          "p_up_threshold": 0.55, "p_dn_threshold": 0.45}),
        NodeSpec(id="btc_gate", type="DirectionGate",
                 params={"allow_long": True, "allow_short": True}),
        NodeSpec(id="btc_risk", type="RiskATR",
                 params={"sl_mult": 2.0, "tp_mult": 4.0, "fraction": 0.005, "capital": 10000}),
        NodeSpec(id="btc_paper", type="PaperTrader", params={}),
        NodeSpec(id="btc_record", type="RecordDecision",
                 params={"db_path": "/app/data/v4_decisions.db"}),
        NodeSpec(id="ai_analyst", type="LLMNode",
                 params={"system_prompt": "You are a crypto trading analyst.",
                          "user_prompt": "Market: {inputs}", "model": "phi4:latest",
                          "temperature": 0.3, "max_tokens": 256}),
        NodeSpec(id="short_signal", type="SignalConstant", params={"signal": "short"}),
        NodeSpec(id="short_gate", type="DirectionGate",
                 params={"allow_long": False, "allow_short": True}),
        NodeSpec(id="short_risk", type="RiskATR",
                 params={"sl_mult": 3.0, "tp_mult": 6.0, "fraction": 0.003, "capital": 10000}),
        NodeSpec(id="short_alert", type="AlertOnly",
                 params={"channels": ["log", "telegram"]}),
    ],
    edges=[
        EdgeSpec(source_node="btc_asset", source_port="symbol",
                 target_node="btc_data", target_port="symbol"),
        EdgeSpec(source_node="btc_data", source_port="ohlcv_5m",
                 target_node="btc_features", target_port="ohlcv"),
        EdgeSpec(source_node="btc_features", source_port="features",
                 target_node="btc_norm", target_port="features"),
        EdgeSpec(source_node="btc_norm", source_port="features_all",
                 target_node="btc_signal", target_port="features_all"),
        EdgeSpec(source_node="btc_norm", source_port="features_all",
                 target_node="btc_regime", target_port="features_all"),
        EdgeSpec(source_node="btc_data", source_port="ohlcv_1h",
                 target_node="btc_trend", target_port="ohlcv_1h"),
        EdgeSpec(source_node="btc_regime", source_port="regime",
                 target_node="btc_signal", target_port="regime"),
        EdgeSpec(source_node="btc_signal", source_port="signal",
                 target_node="btc_gate", target_port="signal"),
        EdgeSpec(source_node="btc_trend", source_port="trend",
                 target_node="btc_gate", target_port="trend"),
        EdgeSpec(source_node="btc_gate", source_port="signal",
                 target_node="btc_risk", target_port="signal"),
        EdgeSpec(source_node="btc_data", source_port="ohlcv_1h",
                 target_node="btc_risk", target_port="ohlcv_1h"),
        EdgeSpec(source_node="btc_asset", source_port="capital",
                 target_node="btc_risk", target_port="capital"),
        EdgeSpec(source_node="btc_risk", source_port="decision",
                 target_node="btc_paper", target_port="decision"),
        EdgeSpec(source_node="btc_asset", source_port="symbol",
                 target_node="btc_paper", target_port="symbol"),
        EdgeSpec(source_node="btc_risk", source_port="decision",
                 target_node="btc_record", target_port="decision"),
        EdgeSpec(source_node="btc_data", source_port="ohlcv_1h",
                 target_node="short_risk", target_port="ohlcv_1h"),
        EdgeSpec(source_node="btc_asset", source_port="capital",
                 target_node="short_risk", target_port="capital"),
        EdgeSpec(source_node="short_signal", source_port="signal",
                 target_node="short_gate", target_port="signal"),
        EdgeSpec(source_node="btc_trend", source_port="trend",
                 target_node="short_gate", target_port="trend"),
        EdgeSpec(source_node="short_gate", source_port="signal",
                 target_node="short_risk", target_port="signal"),
        EdgeSpec(source_node="short_risk", source_port="decision",
                 target_node="short_alert", target_port="decision"),
        EdgeSpec(source_node="btc_risk", source_port="decision",
                 target_node="ai_analyst", target_port="decision"),
        EdgeSpec(source_node="btc_regime", source_port="regime",
                 target_node="ai_analyst", target_port="regime"),
        EdgeSpec(source_node="btc_trend", source_port="trend",
                 target_node="ai_analyst", target_port="trend"),
    ],
)
